#!/bin/sh
set -eu

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  exit 1
}

pass() {
  printf 'PASS: %s\n' "$1"
}

printf 'Reader autoresearch evaluator\n'
printf 'repo: %s\n\n' "$ROOT_DIR"

export GODEBUG="${GODEBUG:+$GODEBUG,}x509negativeserial=1"
export GOCACHE="${GOCACHE:-/private/tmp/alice-go-build-cache}"

printf '1. Building server...\n'
go build -o bin/server ./cmd/server
pass "go build ./cmd/server"

TEMPLATE="internal/templates/reader/interaction.html"
BASE_TEMPLATE="internal/templates/base.html"

printf '\n2. Checking reader layout markers...\n'
rg -q 'reader-workspace' "$TEMPLATE" || fail "missing reader-workspace"
rg -q 'reader-panel-center' "$TEMPLATE" || fail "missing reader-panel-center"
rg -q 'reader-layout-toolbar' "$TEMPLATE" || fail "missing reader-layout-toolbar"
rg -q 'toggle-sections-panel' "$TEMPLATE" || fail "missing sections toggle"
rg -q 'toggle-services-panel' "$TEMPLATE" || fail "missing services toggle"
rg -q 'alice-reader-layout' "$TEMPLATE" || fail "missing persisted layout key"
rg -q 'font-size: 1\.375rem' "$TEMPLATE" || fail "missing central desktop typography marker"
rg -q 'line-height: 1\.78' "$TEMPLATE" || fail "missing central line-height marker"
rg -q 'getGeneratedEverydayExamples' "$TEMPLATE" || fail "missing generated dictionary examples helper"
rg -q 'Generated everyday examples' "$TEMPLATE" || fail "missing generated dictionary examples label"
rg -q 'dictionary-popup-actions' "$TEMPLATE" || fail "missing secondary dictionary action row"
rg -q 'showPicturePopup' "$TEMPLATE" || fail "missing dictionary picture popup action"
rg -q 'lookupWikipediaPicture' "$TEMPLATE" || fail "missing dictionary Wikipedia picture lookup"
rg -q 'generateDictionaryPicture' "$TEMPLATE" || fail "missing dictionary generated picture fallback"
rg -q 'dictionary-popup-picture-container' "$TEMPLATE" || fail "missing dictionary picture container"
rg -q 'dictionary-popup-focus' "$TEMPLATE" || fail "missing dictionary entry/definition focus background"
rg -q 'dictionary-popup-panel-close' "$TEMPLATE" || fail "missing dictionary panel close button"
rg -q 'closeDictionaryPanel' "$TEMPLATE" || fail "missing dictionary panel close helper"
rg -q 'reader-panel-close' "$TEMPLATE" || fail "missing sidebar panel close button"
rg -q 'hideReaderPanelFromHeader' "$TEMPLATE" || fail "missing sidebar panel close helper"
rg -q '#reader-sections-panel \.reader-side-panel' "$TEMPLATE" || fail "missing stable Sections sidebar selector"
rg -F -q 'min-height: min(620px, calc(100vh - 120px))' "$TEMPLATE" || fail "missing stable Sections sidebar minimum height"
rg -q 'min-height: 340px' "$TEMPLATE" || fail "missing stable section snippets list height"
rg -q 'section-page-nav' "$TEMPLATE" || fail "missing section page navigation arrows"
rg -q 'section-page-nav-label' "$TEMPLATE" || fail "missing section page navigation label"
rg -q 'current-page-display-sections' "$TEMPLATE" || fail "missing section page navigation current page display"
HELP_LINE="$(rg -n 'data-bs-target="#servicesHelpCenter"' "$TEMPLATE" | head -n 1 | cut -d: -f1)"
INFO_LINE="$(rg -n 'data-bs-target="#servicesInfoCenter"' "$TEMPLATE" | head -n 1 | cut -d: -f1)"
NAV_LINE="$(rg -n 'data-bs-target="#servicesNavTools"' "$TEMPLATE" | head -n 1 | cut -d: -f1)"
[ "$HELP_LINE" -lt "$INFO_LINE" ] && [ "$INFO_LINE" -lt "$NAV_LINE" ] || fail "Services order should be Help Center, Info Center, Navigation tools"
rg -q 'getShortDefinitionContext' "$TEMPLATE" || fail "missing definition-aware dictionary example helper"
rg -q 'getGeneratedEverydayExampleSets' "$TEMPLATE" || fail "missing varied dictionary example sets helper"
rg -q 'summarizeEtymologyText' "$TEMPLATE" || fail "missing concise derivation summarizer"
rg -q 'renderDerivationPanel' "$TEMPLATE" || fail "missing concise derivation renderer"
rg -q 'example_set_index_' "$TEMPLATE" || fail "missing cycling dictionary example set state"
rg -q 'definition: data.definition' "$TEMPLATE" || fail "missing definition data for generated dictionary examples"
rg -q 'place to sit' "$TEMPLATE" || fail "missing contextual chair-style dictionary example"
rg -q 'Could you bring another' "$TEMPLATE" || fail "missing varied chair dictionary example"
rg -q 'currentIndex % exampleSets.length' "$TEMPLATE" || fail "missing dictionary example cycling logic"
! rg -q 'I heard the word' "$TEMPLATE" || fail "dictionary examples still include generic heard-the-word fallback"
! rg -q 'I used |The word "' "$TEMPLATE" || fail "dictionary examples still include generic word-framing sentences"
rg -q 'ai-chat-add-selection-btn' "$TEMPLATE" || fail "missing AI chat add selected text button"
rg -q 'Add selected text' "$TEMPLATE" || fail "missing explicit AI chat selected text action"
rg -q 'ai-chat-context-bar' "$TEMPLATE" || fail "missing AI chat reading context bar"
rg -q 'Linked to' "$TEMPLATE" || fail "missing AI chat linked context label"
rg -q 'This section' "$TEMPLATE" || fail "missing AI chat section context scope"
rg -q 'This page' "$TEMPLATE" || fail "missing AI chat page context scope"
rg -q 'Selected text' "$TEMPLATE" || fail "missing AI chat selected text context scope"
rg -q 'askAIAboutCurrentContext' "$TEMPLATE" || fail "missing AI context ask action"
rg -q 'getCurrentAIReadingContext' "$TEMPLATE" || fail "missing AI context helper"
rg -q 'ai-chat-legacy-tools' "$TEMPLATE" || fail "missing hidden legacy AI tools container"
rg -q 'ai-chat-starter-btn' "$TEMPLATE" || fail "missing AI empty-state starter actions"
rg -q 'runAIPromptForCurrentContext' "$TEMPLATE" || fail "missing AI empty-state starter helper"
rg -q 'isRangeInsideReaderPage' "$TEMPLATE" || fail "missing AI selected-text reader range guard"
rg -F -q 'highlightSelectedText(selectedRange)' "$TEMPLATE" || fail "missing persistent AI selected-text highlight"
rg -q 'Select a passage in the book' "$TEMPLATE" || fail "missing AI custom selection mode instruction"
! rg -q '<div class="ai-help-tabs' "$TEMPLATE" || fail "AI popup still shows mode tabs"
! rg -q 'id="ai-select-text-btn"' "$TEMPLATE" || fail "AI popup still shows old select-text button"
rg -F -q 'box-shadow: 0 20px 55px rgba(15, 23, 42, 0.28)' "$TEMPLATE" || fail "missing dictionary-style AI assistant shadow"
rg -F -q 'border: 1px solid rgba(31, 41, 55, 0.16)' "$TEMPLATE" || fail "missing dictionary-style AI assistant border"
rg -q 'background: #fafafa' "$TEMPLATE" || fail "missing dictionary-style AI assistant pale header"
rg -q 'reader-service-popup' "$TEMPLATE" || fail "missing dictionary-style service popup class"
SERVICE_POPUP_COUNT="$(rg -c 'modal-content reader-service-popup' "$TEMPLATE")"
[ "$SERVICE_POPUP_COUNT" -ge 5 ] || fail "expected service popup styling on all Reader service modals"
rg -q '\.reader-service-popup \.modal-header' "$TEMPLATE" || fail "missing service popup dictionary-style header"
rg -q '\.reader-service-popup \.modal-title' "$TEMPLATE" || fail "missing service popup dictionary-style title"
! rg -q 'Press Enter to add to chat' "$TEMPLATE" || fail "AI chat still tells reader to press Enter to add selected text"
! rg -q 'new bootstrap\.Modal\(modalElement' "$TEMPLATE" || fail "AI selected-text spark still opens legacy missing modal"
rg -q "popup.style.top = '42%'" "$TEMPLATE" || fail "missing centered dictionary popup placement"
rg -F -q 'width: min(540px, calc(100vw - 32px))' "$TEMPLATE" || fail "missing prominent dictionary popup width"
rg -F -q '{{block "main_class"' "$BASE_TEMPLATE" || fail "missing base main_class override"
pass "reader template markers"

if [ "${BASE_URL:-}" ]; then
  printf '\n3. Checking live app at %s...\n' "$BASE_URL"
  HEALTH_BODY="$(mktemp "${TMPDIR:-/tmp}/alice-health.XXXXXX")"
  PAGE_BODY="$(mktemp "${TMPDIR:-/tmp}/alice-reader.XXXXXX")"

  HEALTH_CODE="$(curl -L --noproxy '*' -sS -o "$HEALTH_BODY" -w '%{http_code}' "$BASE_URL/health")"
  [ "$HEALTH_CODE" = "200" ] || fail "health returned HTTP $HEALTH_CODE"
  rg -q '"status":"ok"' "$HEALTH_BODY" || fail "health did not report status ok"
  pass "live health"

  PAGE_CODE="$(curl -L --noproxy '*' -sS -o "$PAGE_BODY" -w '%{http_code}' "$BASE_URL/reader/interaction")"
  [ "$PAGE_CODE" = "200" ] || fail "reader interaction returned HTTP $PAGE_CODE"
  rg -q 'reader-layout-toolbar' "$PAGE_BODY" || fail "live page missing reader-layout-toolbar"
  rg -q 'Hide sections' "$PAGE_BODY" || fail "live page missing Hide sections"
  rg -q 'reader-panel-center' "$PAGE_BODY" || fail "live page missing reader-panel-center"
  rg -q 'Generated everyday examples' "$PAGE_BODY" || fail "live page missing generated dictionary examples"
  rg -q 'dictionary-popup-actions' "$PAGE_BODY" || fail "live page missing secondary dictionary action row"
  rg -q 'showPicturePopup' "$PAGE_BODY" || fail "live page missing dictionary picture popup action"
  rg -q 'lookupWikipediaPicture' "$PAGE_BODY" || fail "live page missing dictionary Wikipedia picture lookup"
  rg -q 'generateDictionaryPicture' "$PAGE_BODY" || fail "live page missing dictionary generated picture fallback"
  rg -q 'dictionary-popup-picture-container' "$PAGE_BODY" || fail "live page missing dictionary picture container"
  rg -q 'dictionary-popup-focus' "$PAGE_BODY" || fail "live page missing dictionary entry/definition focus background"
  rg -q 'dictionary-popup-panel-close' "$PAGE_BODY" || fail "live page missing dictionary panel close button"
  rg -q 'reader-panel-close' "$PAGE_BODY" || fail "live page missing sidebar panel close button"
  rg -q '#reader-sections-panel \.reader-side-panel' "$PAGE_BODY" || fail "live page missing stable Sections sidebar selector"
  rg -F -q 'min-height: min(620px, calc(100vh - 120px))' "$PAGE_BODY" || fail "live page missing stable Sections sidebar minimum height"
  rg -q 'min-height: 340px' "$PAGE_BODY" || fail "live page missing stable section snippets list height"
  rg -q 'section-page-nav' "$PAGE_BODY" || fail "live page missing section page navigation arrows"
  rg -q 'section-page-nav-label' "$PAGE_BODY" || fail "live page missing section page navigation label"
  rg -q 'current-page-display-sections' "$PAGE_BODY" || fail "live page missing section page navigation current page display"
  LIVE_HELP_LINE="$(rg -n 'data-bs-target="#servicesHelpCenter"' "$PAGE_BODY" | head -n 1 | cut -d: -f1)"
  LIVE_INFO_LINE="$(rg -n 'data-bs-target="#servicesInfoCenter"' "$PAGE_BODY" | head -n 1 | cut -d: -f1)"
  LIVE_NAV_LINE="$(rg -n 'data-bs-target="#servicesNavTools"' "$PAGE_BODY" | head -n 1 | cut -d: -f1)"
  [ "$LIVE_HELP_LINE" -lt "$LIVE_INFO_LINE" ] && [ "$LIVE_INFO_LINE" -lt "$LIVE_NAV_LINE" ] || fail "live Services order should be Help Center, Info Center, Navigation tools"
  rg -q 'getShortDefinitionContext' "$PAGE_BODY" || fail "live page missing definition-aware dictionary example helper"
  rg -q 'getGeneratedEverydayExampleSets' "$PAGE_BODY" || fail "live page missing varied dictionary example sets helper"
  rg -q 'summarizeEtymologyText' "$PAGE_BODY" || fail "live page missing concise derivation summarizer"
  rg -q 'renderDerivationPanel' "$PAGE_BODY" || fail "live page missing concise derivation renderer"
  rg -q 'example_set_index_' "$PAGE_BODY" || fail "live page missing cycling dictionary example set state"
  rg -q 'definition: data.definition' "$PAGE_BODY" || fail "live page missing definition data for generated dictionary examples"
  rg -q 'place to sit' "$PAGE_BODY" || fail "live page missing contextual chair-style dictionary example"
  rg -q 'Could you bring another' "$PAGE_BODY" || fail "live page missing varied chair dictionary example"
  rg -q 'currentIndex % exampleSets.length' "$PAGE_BODY" || fail "live page missing dictionary example cycling logic"
  ! rg -q 'I heard the word' "$PAGE_BODY" || fail "live dictionary examples still include generic heard-the-word fallback"
  ! rg -q 'I used |The word "' "$PAGE_BODY" || fail "live dictionary examples still include generic word-framing sentences"
  rg -q 'ai-chat-add-selection-btn' "$PAGE_BODY" || fail "live page missing AI chat add selected text button"
  rg -q 'Add selected text' "$PAGE_BODY" || fail "live page missing explicit AI chat selected text action"
  rg -q 'ai-chat-context-bar' "$PAGE_BODY" || fail "live page missing AI chat reading context bar"
  rg -q 'Linked to' "$PAGE_BODY" || fail "live page missing AI chat linked context label"
  rg -q 'This section' "$PAGE_BODY" || fail "live page missing AI chat section context scope"
  rg -q 'This page' "$PAGE_BODY" || fail "live page missing AI chat page context scope"
  rg -q 'Selected text' "$PAGE_BODY" || fail "live page missing AI chat selected text context scope"
  rg -q 'askAIAboutCurrentContext' "$PAGE_BODY" || fail "live page missing AI context ask action"
  rg -q 'getCurrentAIReadingContext' "$PAGE_BODY" || fail "live page missing AI context helper"
  rg -q 'ai-chat-legacy-tools' "$PAGE_BODY" || fail "live page missing hidden legacy AI tools container"
  rg -q 'ai-chat-starter-btn' "$PAGE_BODY" || fail "live page missing AI empty-state starter actions"
  rg -q 'runAIPromptForCurrentContext' "$PAGE_BODY" || fail "live page missing AI empty-state starter helper"
  rg -q 'isRangeInsideReaderPage' "$PAGE_BODY" || fail "live page missing AI selected-text reader range guard"
  rg -F -q 'highlightSelectedText(selectedRange)' "$PAGE_BODY" || fail "live page missing persistent AI selected-text highlight"
  rg -q 'Select a passage in the book' "$PAGE_BODY" || fail "live page missing AI custom selection mode instruction"
  ! rg -q '<div class="ai-help-tabs' "$PAGE_BODY" || fail "live AI popup still shows mode tabs"
  ! rg -q 'id="ai-select-text-btn"' "$PAGE_BODY" || fail "live AI popup still shows old select-text button"
  rg -F -q 'box-shadow: 0 20px 55px rgba(15, 23, 42, 0.28)' "$PAGE_BODY" || fail "live page missing dictionary-style AI assistant shadow"
  rg -F -q 'border: 1px solid rgba(31, 41, 55, 0.16)' "$PAGE_BODY" || fail "live page missing dictionary-style AI assistant border"
  rg -q 'background: #fafafa' "$PAGE_BODY" || fail "live page missing dictionary-style AI assistant pale header"
  rg -q 'reader-service-popup' "$PAGE_BODY" || fail "live page missing dictionary-style service popup class"
  LIVE_SERVICE_POPUP_COUNT="$(rg -c 'modal-content reader-service-popup' "$PAGE_BODY")"
  [ "$LIVE_SERVICE_POPUP_COUNT" -ge 5 ] || fail "live page expected service popup styling on all Reader service modals"
  rg -q '\.reader-service-popup \.modal-header' "$PAGE_BODY" || fail "live page missing service popup dictionary-style header"
  rg -q '\.reader-service-popup \.modal-title' "$PAGE_BODY" || fail "live page missing service popup dictionary-style title"
  ! rg -q 'Press Enter to add to chat' "$PAGE_BODY" || fail "live page still tells reader to press Enter to add selected text"
  ! rg -q 'new bootstrap\.Modal\(modalElement' "$PAGE_BODY" || fail "live page AI selected-text spark still opens legacy missing modal"
  pass "live reader interaction markers"
else
  printf '\n3. Skipping live app checks. Set BASE_URL=http://localhost:8080 or BASE_URL=https://alice-suite-go.onrender.com to enable.\n'
fi

printf '\nReader autoresearch evaluator passed.\n'
